site_name: HyperCluster
theme: readthedocs
markdown_extensions:
  - toc:
    permalink: "#"
    baselevel: 1
    separator: "_"
markdown_extensions:
  - admonition
nav:
  - Introduction: intro.md
  - Key Concepts: keyconc.md
  - User Guides: guides/index.md
  - API:
    - 'Version 0.6.X.X': 'guides/api-v0.6.x.x.md'
  - Glossary: glossary.md
  - Explorer: explorer.md
  - Release notes: release-notes.md
  - License: license.md
  - Tutorials: tutorials/index.md

